{"name": "test_delete_contact_unauthorized", "status": "passed", "description": "TC026: Unsuccessful delete contact without auth token", "attachments": [{"name": "log", "source": "635a9dc4-a9d5-4323-a995-c9faefd22491-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "412b3a93-0948-49d7-b3a6-5966a4075e31-attachment.txt", "type": "text/plain"}], "start": 1733906259533, "stop": 1733906259665, "uuid": "8584e6f8-c7c1-4d8a-a96e-a24b2011a07b", "historyId": "ddb2a9ee5eb1693b4a2ec24f0c45143c", "testCaseId": "ddb2a9ee5eb1693b4a2ec24f0c45143c", "fullName": "API.test_api#test_delete_contact_unauthorized", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-0LB7JBM"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}