{"name": "test_update_contact_unauthorized_put_method", "status": "passed", "description": "TC021: Unsuccessful update contact without auth token \n    and using PUT method", "attachments": [{"name": "log", "source": "df68d025-3fb6-4a48-af61-c6ecb9f0f422-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8364148d-6503-4826-bb3d-f2f0473ed325-attachment.txt", "type": "text/plain"}], "start": 1733918925091, "stop": 1733918925651, "uuid": "1ad3d758-4a27-4fb7-b362-043a053e09ed", "historyId": "5ec8d11746d14b101f73c31211358a24", "testCaseId": "5ec8d11746d14b101f73c31211358a24", "fullName": "API.test_api#test_update_contact_unauthorized_put_method", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "5cbf70c9ed4a"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}